FROM node:16 as build
WORKDIR /app 

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --production

COPY . .
RUN npm run build
# RUN npm install

# CMD ["npm", "run", "start"]

#NGINX Web Server
FROM nginx:1.20-alpine as prod
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]